import Img from '../assets/testing.jpg';

const sampleData = [
  { id: 1, title: 'Global Political Shift', urlToImage: Img, category: 'World', section: 'watch_card' },
  { id: 2, title: 'Climate Change Impact', urlToImage: Img, category: 'World', section: 'watch_card' },
  { id: 3, title: 'World Economy Trends', urlToImage: Img, category: 'World', section: 'watch_card' },
  { id: 4, title: 'International Relations', urlToImage: Img, category: 'World', section: 'watch_card' },
  { id: 5, title: 'Global Health Issues', urlToImage: Img, category: 'World', section: 'watch_card' },
  { id: 6, title: 'World News Highlights', urlToImage: Img, category: 'World', section: 'liveNewsItem_card' },
  { id: 7, title: 'Global Technology Advances', urlToImage: Img, category: 'World', section: 'TopTrending_card' },
  { id: 8, title: 'World Travel Updates', urlToImage: Img, category: 'World', section: 'TopTrending_card' },
  { id: 9, title: 'International Sports Events', urlToImage: Img, category: 'World', section: 'TopTrending_card' },
  { id: 10, title: 'Global Cultural Events', urlToImage: Img, category: 'World', section: 'TopTrending_card' },

  { id: 11, title: 'Political Scandals', urlToImage: Img, category: 'Politics', section: 'TopTrending_card' },
  { id: 12, title: 'Election Updates', urlToImage: Img, category: 'Politics', section: 'TopTrending_card'},
  { id: 13, title: 'Government Policies', urlToImage: Img, category: 'Politics', section: 'TopTrending_card' },
  { id: 14, title: 'Political Debates', urlToImage: Img, category: 'Politics', section: 'TopTrending_card' },
  { id: 15, title: 'Legislative Changes', urlToImage: Img, category: 'Politics', section: 'TopTrending_card' },
  { id: 16, title: 'Political Campaigns', urlToImage: Img, category: 'Politics', section: 'TopTrending_card' },
  { id: 17, title: 'International Political News', urlToImage: Img, category: 'Politics', section: 'TopTrending_card' },
  { id: 18, title: 'Public Protests', urlToImage: Img, category: 'Politics', section: 'liveNewsItem_card' },
  { id: 19, title: 'Political Analysis', urlToImage: Img, category: 'Politics', section: 'SpotLight_card' },

  { id: 20, title: 'Market Trends', urlToImage: Img, category: 'Business', section: 'Topstories_card' },
  { id: 21, title: 'Startup News', urlToImage: Img, category: 'Business', section: 'Topstories_card' },
  { id: 22, title: 'Business Innovations', urlToImage: Img, category: 'Business', section: 'Topstories_card' },
  { id: 23, title: 'Economic Policies', urlToImage: Img, category: 'Business', section: 'FirstStories_card' },
  { id: 24, title: 'Corporate News', urlToImage: Img, category: 'Business', section: 'SecondStories_card' },
  { id: 25, title: 'Investment Opportunities', urlToImage: Img, category: 'Business', section: 'singleCardItemOne_card' },
  { id: 26, title: 'Business Conferences', urlToImage: Img, category: 'Business', section: 'singleCardItemOne_card' },
  { id: 27, title: 'Business Leadership', urlToImage: Img, category: 'Business', section: 'singleCardItemOne_card' },
  { id: 28, title: 'Retail Updates', urlToImage: Img, category: 'Business', section: 'singleCardItemTwo_card' },
  { id: 29, title: 'Tech Startups', urlToImage: Img, category: 'Business', section: 'singleCardItemTwo_card' },

  { id: 30, title: 'Latest Gadgets', urlToImage: Img, category: 'Technology', section: 'singleCardItemTwo_card' },
  // { id: 31, title: 'Tech Innovations', urlToImage: Img, category: 'Technology', section: 'rightbarTrending' },
  { id: 32, title: 'AI Developments', urlToImage: Img, category: 'Technology', section: 'cardThreeData_card' },
  { id: 33, title: 'Cybersecurity Updates', urlToImage: Img, category: 'Technology', section: 'cardTwoData_card' },
  { id: 34, title: 'Software Releases', urlToImage: Img, category: 'Technology', section: 'cardTwoData_card' },
  { id: 35, title: 'Tech Conferences', urlToImage: Img, category: 'Technology', section: 'cardTwoData_card' },
  { id: 36, title: 'Gadget Reviews', urlToImage: Img, category: 'Technology', section: 'cardTwoData_card' },
  { id: 37, title: 'Tech Industry Trends', urlToImage: Img, category: 'Technology', section: 'cardTwoData_card' },
  { id: 38, title: 'Tech Company News', urlToImage: Img, category: 'Technology', section: 'cardTwoData_card' },
  { id: 39, title: 'Innovative Startups', urlToImage: Img, category: 'Technology', section: 'cardTwoData_card' },

  { id: 40, title: 'Football Scores', urlToImage: Img, category: 'Sports', section: 'opiniondata_card' },
  { id: 41, title: 'Olympic Games Updates', urlToImage: Img, category: 'Sports', section: 'opiniondata_card'  },
  { id: 42, title: 'Tennis Tournaments', urlToImage: Img, category: 'Sports', section: 'opiniondata_card' },
  { id: 43, title: 'Basketball Highlights', urlToImage: Img, category: 'Sports', section: 'opiniondata_card' },
  { id: 44, title: 'Sports Injuries', urlToImage: Img, category: 'Sports', section: 'Mainstories_card' },
  { id: 45, title: 'Athlete Profiles', urlToImage: Img, category: 'Sports', section: 'Mainstories_card' },
  { id: 46, title: 'Sports Events Schedule', urlToImage: Img, category: 'Sports', section: 'Mainstories_card' },
  { id: 47, title: 'Esports News', urlToImage: Img, category: 'Sports', section: 'Mainstories_card' },
  { id: 48, title: 'Sports Betting Tips', urlToImage: Img, category: 'Sports', section: 'Mainstories_card' },
  // { id: 49, title: 'Sports Achievements', urlToImage: Img, category: 'Sports', section: 'Mainstories_card' },

  { id: 50, title: 'Health Tips', urlToImage: Img, category: 'Health', section: 'Tips' },
  { id: 51, title: 'Medical Breakthroughs', urlToImage: Img, category: 'Health', section: 'Breakthroughs' },
  { id: 52, title: 'Fitness Trends', urlToImage: Img, category: 'Health', section: 'Fitness' },
  { id: 53, title: 'Diet and Nutrition', urlToImage: Img, category: 'Health', section: 'Diet' },
  { id: 54, title: 'Mental Health Awareness', urlToImage: Img, category: 'Health', section: 'Mental Health' },
  { id: 55, title: 'Health Research', urlToImage: Img, category: 'Health', section: 'Research' },
  { id: 56, title: 'Healthcare Policies', urlToImage: Img, category: 'Health', section: 'Policies' },
  { id: 57, title: 'Health and Wellness', urlToImage: Img, category: 'Health', section: 'Wellness' },
  { id: 58, title: 'Medical Events', urlToImage: Img, category: 'Health', section: 'Events' },
  { id: 59, title: 'Health Gadgets', urlToImage: Img, category: 'Health', section: 'Gadgets' },

  { id: 60, title: 'Educational Trends', urlToImage: Img, category: 'Education', section: 'Trends' },
  { id: 61, title: 'Student Life', urlToImage: Img, category: 'Education', section: 'Student Life' },
  { id: 62, title: 'Online Learning', urlToImage: Img, category: 'Education', section: 'Online Learning' },
  { id: 63, title: 'School Events', urlToImage: Img, category: 'Education', section: 'Events' },
  { id: 64, title: 'Educational Innovations', urlToImage: Img, category: 'Education', section: 'Innovations' },
  { id: 65, title: 'Scholarships', urlToImage: Img, category: 'Education', section: 'Scholarships' },
  { id: 66, title: 'Teaching Methods', urlToImage: Img, category: 'Education', section: 'Teaching' },
  { id: 67, title: 'Higher Education', urlToImage: Img, category: 'Education', section: 'Higher Education' },
  { id: 68, title: 'Education Policy', urlToImage: Img, category: 'Education', section: 'Policy' },
  { id: 69, title: 'Student Success Stories', urlToImage: Img, category: 'Education', section: 'Success Stories' },

  { id: 70, title: 'Environmental Issues', urlToImage: Img, category: 'Environment', section: 'Issues' },
  { id: 71, title: 'Climate Action', urlToImage: Img, category: 'Environment', section: 'Climate Action' },
  { id: 72, title: 'Wildlife Conservation', urlToImage: Img, category: 'Environment', section: 'Wildlife' },
  { id: 73, title: 'Green Technologies', urlToImage: Img, category: 'Environment', section: 'Technologies' },
  { id: 74, title: 'Sustainability Practices', urlToImage: Img, category: 'Environment', section: 'Sustainability' },
  { id: 75, title: 'Renewable Energy', urlToImage: Img, category: 'Environment', section: 'Renewable Energy' },
  { id: 76, title: 'Environmental Policies', urlToImage: Img, category: 'Environment', section: 'Policies' },
  { id: 77, title: 'Environmental Activism', urlToImage: Img, category: 'Environment', section: 'Activism' },
  { id: 78, title: 'Climate Change Effects', urlToImage: Img, category: 'Environment', section: 'Climate Change' },
  { id: 79, title: 'Green Living', urlToImage: Img, category: 'Environment', section: 'Living' },

  { id: 80, title: 'Religious Events', urlToImage: Img, category: 'Religion', section: 'Events' },
  { id: 81, title: 'Faith-based Initiatives', urlToImage: Img, category: 'Religion', section: 'Initiatives' },
  { id: 82, title: 'Interfaith Dialogues', urlToImage: Img, category: 'Religion', section: 'Dialogues' },
  { id: 83, title: 'Religious News', urlToImage: Img, category: 'Religion', section: 'News' },
  { id: 84, title: 'Spiritual Practices', urlToImage: Img, category: 'Religion', section: 'Practices' },
  { id: 85, title: 'Religious Figures', urlToImage: Img, category: 'Religion', section: 'Figures' },
  { id: 86, title: 'Religious Festivals', urlToImage: Img, category: 'Religion', section: 'Festivals' },
  { id: 87, title: 'Religious Education', urlToImage: Img, category: 'Religion', section: 'Education' },
  { id: 88, title: 'Faith and Society', urlToImage: Img, category: 'Religion', section: 'Society' },
  { id: 89, title: 'Religious Literature', urlToImage: Img, category: 'Religion', section: 'Literature' },

  { id: 90, title: 'Entertainment News', urlToImage: Img, category: 'Entertainment', section: 'News' },
  { id: 91, title: 'Celebrity Gossip', urlToImage: Img, category: 'Entertainment', section: 'Gossip' },
  { id: 92, title: 'Movie Reviews', urlToImage: Img, category: 'Entertainment', section: 'Movies' },
  { id: 93, title: 'TV Shows Updates', urlToImage: Img, category: 'Entertainment', section: 'TV Shows' },
  { id: 94, title: 'Music Releases', urlToImage: Img, category: 'Entertainment', section: 'Music' },
  { id: 95, title: 'Entertainment Events', urlToImage: Img, category: 'Entertainment', section: 'Events' },
  { id: 96, title: 'Celebrity Interviews', urlToImage: Img, category: 'Entertainment', section: 'Interviews' },
  { id: 97, title: 'Entertainment Industry Trends', urlToImage: Img, category: 'Entertainment', section: 'Trends' },
  { id: 98, title: 'Gossip Columns', urlToImage: Img, category: 'Entertainment', section: 'Columns' },
  { id: 99, title: 'Entertainment Awards', urlToImage: Img, category: 'Entertainment', section: 'Awards' },
];

export default sampleData;
